"""empty message

Revision ID: d13fc09f98bd
Revises: 
Create Date: 2017-04-01 21:38:14.893000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13fc09f98bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assetable_id', sa.Integer(), nullable=True),
    sa.Column('assetable_type', sa.String(length=30), nullable=True),
    sa.Column('data_file_name', sa.String(length=255), nullable=True),
    sa.Column('data_content_type', sa.String(length=255), nullable=True),
    sa.Column('data_file_size', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=30), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('description_en_US', sa.Text(), nullable=True),
    sa.Column('description_fr_FR', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Assets_asset_type'), 'Assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_Assets_assetable_id'), 'Assets', ['assetable_id'], unique=False)
    op.create_index(op.f('ix_Assets_assetable_type'), 'Assets', ['assetable_type'], unique=False)
    op.create_index(op.f('ix_Assets_is_active'), 'Assets', ['is_active'], unique=False)
    op.create_table('Sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('title_en_US', sa.String(length=255), nullable=True),
    sa.Column('title_fr_FR', sa.String(length=255), nullable=True),
    sa.Column('description_en_US', sa.Text(), nullable=True),
    sa.Column('description_fr_FR', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sections_description_en_US'), 'Sections', ['description_en_US'], unique=False)
    op.create_index(op.f('ix_Sections_description_fr_FR'), 'Sections', ['description_fr_FR'], unique=False)
    op.create_index(op.f('ix_Sections_is_active'), 'Sections', ['is_active'], unique=False)
    op.create_index(op.f('ix_Sections_slug'), 'Sections', ['slug'], unique=True)
    op.create_index(op.f('ix_Sections_title_en_US'), 'Sections', ['title_en_US'], unique=True)
    op.create_index(op.f('ix_Sections_title_fr_FR'), 'Sections', ['title_fr_FR'], unique=True)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['Sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_is_active'), 'Users', ['is_active'], unique=False)
    op.create_index(op.f('ix_Users_locale'), 'Users', ['locale'], unique=False)
    op.create_index(op.f('ix_Users_timezone'), 'Users', ['timezone'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_timezone'), table_name='Users')
    op.drop_index(op.f('ix_Users_locale'), table_name='Users')
    op.drop_index(op.f('ix_Users_is_active'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Sections_title_fr_FR'), table_name='Sections')
    op.drop_index(op.f('ix_Sections_title_en_US'), table_name='Sections')
    op.drop_index(op.f('ix_Sections_slug'), table_name='Sections')
    op.drop_index(op.f('ix_Sections_is_active'), table_name='Sections')
    op.drop_index(op.f('ix_Sections_description_fr_FR'), table_name='Sections')
    op.drop_index(op.f('ix_Sections_description_en_US'), table_name='Sections')
    op.drop_table('Sections')
    op.drop_index(op.f('ix_Assets_is_active'), table_name='Assets')
    op.drop_index(op.f('ix_Assets_assetable_type'), table_name='Assets')
    op.drop_index(op.f('ix_Assets_assetable_id'), table_name='Assets')
    op.drop_index(op.f('ix_Assets_asset_type'), table_name='Assets')
    op.drop_table('Assets')
    # ### end Alembic commands ###
